Repository AlternativeFFFF/Alt-F4, pull requests merged in 2020-10, with the labels that each got.

#184 Issue Nr7
  _drafts/2020-10-02-ALTF4-7.md
  assets/ALTF4/7/thumbnail.jpg
Labels: impact:submission, status:copy-edited

#182 Multiplayer event
  submissions/Altf47BCGevent/Altf4no7BCGrev1.md
Labels: impact:submission, status:copy-edited

#144 Add Yuoki Industries mod spotlight assets
  submissions/YuokiIndustries/YuokiIndustries.md
Labels: impact:submission, status:copy-edited

#176 Shipping Plates
  submissions/shipping_plates/shipping_plates.md
Labels: impact:submission, status:copy-edited

#189 Translation push
  _posts/de/2020-10-02-ALTF4-7.md
  _posts/es/2020-10-02-ALTF4-7.md
  _posts/fr/2020-10-02-ALTF4-7.md
Labels: impact:translation

#192 Science pack standardized
  _posts/zh/2020-08-21-ALTF4-1.md
  _posts/zh/2020-09-11-ALTF4-4.md
  _posts/zh/2020-09-25-ALTF4-6.md
Labels: impact:translation

#197 Improvements for Chinese fonts
  _layouts/default.html
  _sass/text.scss
Labels: platform:website

#207 Fixed reddit img embed
  _includes/head.html
  assets/GLOBAL/img/Alt-F4-icon_colour.png
Labels: impact:bug, platform:website

#199 Translation push
  _posts/it/2020-10-02-ALTF4-7.md
Labels: impact:translation

#183 Page Not Translated Banner
  _data/cs/locale.yml
  _data/de/locale.yml
  _data/en/locale.yml
  _data/es/locale.yml
  _data/fr/locale.yml
  _data/it/locale.yml
  _data/pl/locale.yml
  _data/ru/locale.yml
  _data/ua/locale.yml
  _data/zh/locale.yml
  _layouts/post.html
  _sass/text.scss
Labels: platform:website

#202 Issue 8 - Love letter
  .gitignore
  _drafts/2020-10-09-ALTF4-8.md
  assets/ALTF4/8/thumbnail.jpg
Labels: impact:submission, status:copy-edited

#185 Loveletter: Trains!
  submissions/conor_loveletter/letter.md
Labels: impact:submission, status:copy-edited

#200 Loveletter: Community
  submissions/loveletter_zirr/loveletter_zirr.md
Labels: impact:submission, status:copy-edited

#201 Loveletter: Modding
  submissions/loveletter_therenas/loveletter_therenas.md
Labels: impact:submission, status:copy-edited

#206 Loveletter: Freedom to Create
  submissions/loveletter_trupen/loveletter_trupen.md
Labels: impact:submission, status:copy-edited

#208 Loveletter: Beginning
  submissions/loveletter_recon/loveletter_recon.md
Labels: impact:submission, status:copy-edited

#209 Loveletter: Community 2, Electric Boogaloo
  submissions/dummy_submission/loveletter_toblerone/loveletter_toblerone.md
Labels: impact:submission, status:copy-edited

#210 Loveletter: No Fluff
  submissions/loveletter_stringweasel/loveletter_stringweasel.md
Labels: impact:submission, status:copy-edited

#211 Loveletter: Multiplayer
  submissions/loveletter_theKool/loveletter_theKool.md
Labels: impact:submission, status:copy-edited

#212 Loveletter: Attention to Detail
  submissions/loveletter_dexter/loveletter_dexter.md
Labels: impact:submission, status:copy-edited

#203 Loveletter: Optimization
  submissions/loveletter_twisted/loveletter_twisted.md
Labels: impact:submission, status:copy-edited

#204 Loveletter: Escapism
  submissions/loveletter_frank/loveletter_frank.md
Labels: impact:submission, status:copy-edited

#205 Loveletter: Burner Inserters
  submissions/loveletter_goose/loveletter_goose.md
Labels: impact:submission, status:copy-edited

#213 Added second discord notify for Factorio discord
  .github/workflows/Release_Notify.yml
Labels: platform:discord, platform:github

#219 Translation Push - Issue 8
  _posts/de/2020-10-09-ALTF4-8.md
  _posts/es/2020-10-09-ALTF4-8.md
  _posts/fr/2020-10-09-ALTF4-8.md
Labels: impact:translation

#221 Issue 8 - IT
  _posts/it/it.2020-10-09-ALTF4-8.md
Labels: impact:translation

#220 Chinese Translation - Issue 8
  _posts/zh/2020-10-09-ALTF4-8.md
Labels: impact:translation

#224 #171: Fix author left spacing when DOM differs
  _sass/text.scss
Labels: impact:bug, platform:website

#226 Use `em` not `i` tags
  _includes/navbar.html
  _sass/text.scss
Labels: impact:accessibility, platform:website

#218 added proofreader field
  _config.yml
  _data/de/locale.yml
  _data/en/locale.yml
  _data/es/locale.yml
  _data/fr/locale.yml
  _data/it/locale.yml
  _data/ru/locale.yml
  _data/ua/locale.yml
  _data/zh/locale.yml
  _drafts/compare.md
  _includes/author.html
Labels: platform:website

#229 Update about page
  _data/en/locale.yml
Labels: impact:enhancement, platform:website

#231 CS locale update
  _data/cs/locale.yml
Labels: impact:translation

#181 Nauvis Archives: Our Own Jargon
  submissions/nauvis_archives_our_own_jargon/media/first_steps.png
  submissions/nauvis_archives_our_own_jargon/media/nauvis_day.jpg
  submissions/nauvis_archives_our_own_jargon/nauvis_archives_our_own_jargon.md
Labels: impact:submission, status:copy-edited

#188 Translation process
  submissions/translation_process/translation_process.md
Labels: impact:submission, status:copy-edited

#230 Issue 9
  _drafts/2020-10-16-ALTF4-9.md
Labels: impact:submission, status:copy-edited

#234 Translation push - Issue 9
  _posts/de/2020-10-16-ALTF4-9.md
  _posts/es/2020-10-16-ALTF4-9.md
  _posts/fr/2020-10-16-ALTF4-9.md
Labels: impact:translation

#232 Chinese Translation - Issue 9
  _posts/zh/2020-10-16-ALTF4-9.md
Labels: impact:translation

#235 Internal Links with localization
  _posts/cs/2020-08-28-ALTF4-2.md
  _posts/de/2020-10-09-ALTF4-8.md
  _posts/es/2020-08-28-ALTF4-2.md
  _posts/es/2020-09-11-ALTF4-4.md
  _posts/es/2020-10-02-ALTF4-7.md
  _posts/es/2020-10-09-ALTF4-8.md
  _posts/fr/2020-09-11-ALTF4-4.md
  _posts/fr/2020-09-18-ALTF4-5.md
  _posts/fr/2020-10-02-ALTF4-7.md
  _posts/fr/2020-10-09-ALTF4-8.md
  _posts/it/2020-08-28-ALTF4-2.md
  _posts/it/2020-09-18-ALTF4-5.md
  _posts/it/2020-10-02-ALTF4-7.md
  _posts/it/2020-10-09-ALTF4-8.md
  _posts/zh/2020-08-28-ALTF4-2.md
  _posts/zh/2020-09-11-ALTF4-4.md
  _posts/zh/2020-09-18-ALTF4-5.md
  _posts/zh/2020-10-02-ALTF4-7.md
Labels: impact:translation, platform:website

#239 Added figure with captions
  _includes/figure.html
  _posts/de/2020-10-16-ALTF4-9.md
  _posts/en/2020-10-16-ALTF4-9.md
  _posts/es/2020-10-16-ALTF4-9.md
  _posts/fr/2020-10-16-ALTF4-9.md
  _posts/zh/2020-10-16-ALTF4-9.md
  _sass/base.scss
Labels: platform:website

#243 IT Issue9
  _posts/it/2020-10-16-ALTF4-9.md
Labels: impact:translation

#245 FR/ES/IT/ZH Issue 5
  _posts/es/2020-09-18-ALTF4-5.md
  _posts/fr/2020-09-18-ALTF4-5.md
  _posts/it/2020-09-18-ALTF4-5.md
  _posts/zh/2020-09-18-ALTF4-5.md
Labels: impact:translation

#242 Locale update (About section)
  _data/cs/locale.yml
  _data/de/locale.yml
  _data/es/locale.yml
  _data/fr/locale.yml
  _data/it/locale.yml
  _data/pl/locale.yml
  _data/ru/locale.yml
  _data/ua/locale.yml
Labels: impact:translation

#247 Chinese locale.yml update
  _data/zh/locale.yml
Labels: impact:translation

#246 wrapped countdown in paragraph tags
  _includes/countdown.html
  _posts/de/2020-10-02-ALTF4-7.md
  _posts/en/2020-09-04-ALTF4-3.md
  _posts/en/2020-10-02-ALTF4-7.md
  _posts/es/2020-09-04-ALTF4-3.md
  _posts/es/2020-10-02-ALTF4-7.md
  _posts/fr/2020-09-04-ALTF4-3.md
  _posts/fr/2020-10-02-ALTF4-7.md
  _posts/it/2020-09-04-ALTF4-3.md
  _posts/it/2020-10-02-ALTF4-7.md
  _posts/ru/2020-09-04-ALTF4-3.md
  _posts/zh/2020-09-04-ALTF4-3.md
  _posts/zh/2020-10-02-ALTF4-7.md
Labels: platform:website

#248 added quotes
  _includes/quote.html
  _sass/base.scss
  _sass/quote.scss
  assets/GLOBAL/css/style.scss
  assets/GLOBAL/img/quot-left-sm.png
  assets/GLOBAL/img/quot-right-sm.png
Labels: platform:website

#238 Nauvis Archives: Jargon Update
  submissions/nauvis_archives_jargon_update/nauvis_archives_jargon_update.md
Labels: impact:submission, status:copy-edited

#240 Border walls
  submissions/Border Walls/border-walls.md
Labels: impact:submission, status:copy-edited

#146 Is Factorio an annoying game?
  submissions/no pain no gain/no pain no gain.md
Labels: impact:submission, status:copy-edited

#252 Chinese Translation - Issue 10
  _posts/zh/2020-10-23-ALTF4-10.md
Labels: impact:translation

#253 Issue 10 - Translation push
  _posts/es/2020-10-23-ALTF4-10.md
  _posts/fr/2020-10-23-ALTF4-10.md
Labels: impact:translation

#251 Locale fix
  _data/cs/locale.yml
  _data/de/locale.yml
  _data/es/locale.yml
  _data/fr/locale.yml
  _data/it/locale.yml
  _data/pl/locale.yml
  _data/ru/locale.yml
  _data/ua/locale.yml
  _data/zh/locale.yml
Labels: impact:translation

#255 DE/ES/FR/ZH Typo Fix
  _posts/de/2020-10-23-ALTF4-10.md
  _posts/es/2020-10-23-ALTF4-10.md
  _posts/fr/2020-10-23-ALTF4-10.md
  _posts/zh/2020-10-23-ALTF4-10.md
Labels: impact:translation

#258 Hack the pagination
  _includes/pagination.html
Labels: platform:website

#244 DE issue 1 to 8
  _posts/de/2020-08-21-ALTF4-1.md
  _posts/de/2020-08-28-ALTF4-2.md
  _posts/de/2020-09-04-ALTF4-3.md
  _posts/de/2020-09-11-ALTF4-4.md
  _posts/de/2020-09-18-ALTF4-5.md
  _posts/de/2020-09-25-ALTF4-6.md
  _posts/de/2020-10-02-ALTF4-7.md
  _posts/de/2020-10-09-ALTF4-8.md
  _posts/de/2020-10-16-ALTF4-9.md
Labels: impact:translation

#257 RU Issue 10
  _posts/ru/2020-10-23-ALTF4-10.md
Labels: impact:translation

#260 sub and sup
  _sass/base.scss
Labels: platform:website

#256 dynamic stuff
  404.html
  _data/de/locale.yml
  _data/en/locale.yml
  _data/es/locale.yml
  _data/fr/locale.yml
  _data/it/locale.yml
  _data/ru/locale.yml
  _data/zh/locale.yml
  _layouts/page.html
Labels: platform:website

#262 NL support (About/config/1st issue)
  _config.yml
  _data/nl/locale_NL.yml
  _posts/nl/2020-08-21-ALTF4-1_NL.md
Labels: impact:translation

#264 IT - Issue10
  _posts/it/2020-10-23-ALTF4-10.md
Labels: impact:translation

#265 Optimize background images
  _sass/base.scss
  assets/GLOBAL/img/bg.jpg
  assets/GLOBAL/img/bg.webp
  assets/GLOBAL/img/mobile-bg.jpg
  assets/GLOBAL/img/mobile-bg.webp
Labels: impact:enhancement, platform:website

#266 Issue 11
  _drafts/2020-10-30-ALTF4-11.md
  assets/ALTF4/11/thumbnail.jpg
Labels: impact:submission, status:copy-edited

#261 A scientific examination of the Factorio world
  submissions/pseudoscience/pseudoscience_non-fiction.md
Labels: impact:submission, status:copy-edited

#227 Nauvis Archives: Outdated Mechanics
  submissions/nauvis_archives_ancient_methodologies/nauvis_archives.md
Labels: impact:submission, status:copy-edited

#267 Issue10 translations
  _posts/es/2020-10-30-ALTF4-11.md
  _posts/fr/2020-10-30-ALTF4-11.md
Labels: impact:translation

#273 Issue11 - FR fix
  _posts/fr/2020-10-30-ALTF4-11.md
Labels: impact:translation

#271 Issue 10 - FR Fix
  _posts/fr/2020-10-23-ALTF4-10.md
Labels: impact:translation

#268 Chinese Translation - Issue 11
  _posts/zh/2020-10-30-ALTF4-11.md
Labels: impact:translation

#274 Issue 11 - DE
  _posts/de/2020-10-30-ALTF4-11.md
Labels: impact:translation
