Repository AlternativeFFFF/Alt-F4, pull requests merged in 2020-09, with the labels that each got.

#38 Fix translation button being active causing navbar to increase in height
  _sass/navbar.scss
Labels: impact:bug, platform:website

#39 Use logo in navbar instead of text (and mobile improvements)
  _includes/navbar.html
  _sass/navbar.scss
  assets/GLOBAL/img/Alt-F4-logo_colour.png
  assets/GLOBAL/img/Alt-F4-logo_white.png
Labels: impact:enhancement, platform:website

#41 Add commas between fields in author section
  _includes/author.html
Labels: impact:enhancement

#47 Updated design to remove header and modernise look
  _data/en/locale.yml
  _includes/header.html
  _includes/navbar.html
  _layouts/default.html
  _sass/navbar.scss
Labels: platform:website

#45 Add countdown module
  _drafts/YYYY-MM-DD-ALT-F4-X.md
  _includes/countdown.html
  _sass/countdown.scss
  assets/GLOBAL/css/style.scss
Labels: impact:enhancement, platform:website

#49 Molten silicon
  submissions/molten_silicon/molten_silicon.md
Labels: impact:submission

#50 Tronparty
  submissions/tronparty/tronparty.md
Labels: impact:submission

#57 Editor Extensions spotlight
  submissions/editor_extensions/editor_extensions.md
Labels: impact:submission

#51 Better media, Diagrams and Math
  Gemfile
  Gemfile.lock
  _config.yml
  _drafts/YYYY-MM-DD-ALT-F4-X.md
  _sass/base.scss
  run.bat
  run.sh
Labels: impact:enhancement, platform:website

#67 fixing #62
  _sass/text.scss
Labels: impact:accessibility, impact:enhancement, platform:website

#68 #66: Change text color to light gray for links in navbar
  _sass/navbar.scss
Labels: impact:accessibility, impact:bug, platform:website

#70 #65: Make navbar text unselectable
  _sass/navbar.scss
Labels: impact:enhancement, platform:website

#78 #77: Fix translation dropdown URL having whitespace at the end
  _includes/navbar.html
Labels: impact:bug, platform:website

#85 Add 'lang' attribute to HTML tag featuring the language code for the current page
  _layouts/default.html
Labels: impact:accessibility, impact:enhancement, platform:website

#86 #80: Fix broken English translation dropdown when switching from non-English language
  _includes/navbar.html
Labels: impact:accessibility, impact:bug, platform:website

#76 Changed font to smaller one and more readable
  _includes/head.html
  _sass/base.scss
  _sass/footer.scss
  _sass/text.scss
  assets/GLOBAL/css/titillium-web.css
  assets/GLOBAL/css/titillium-web/titillium-web-v8-latin-ext_latin-600.eot
  assets/GLOBAL/css/titillium-web/titillium-web-v8-latin-ext_latin-600.svg
  assets/GLOBAL/css/titillium-web/titillium-web-v8-latin-ext_latin-600.ttf
  assets/GLOBAL/css/titillium-web/titillium-web-v8-latin-ext_latin-600.woff
  assets/GLOBAL/css/titillium-web/titillium-web-v8-latin-ext_latin-600.woff2
  assets/GLOBAL/css/titillium-web/titillium-web-v8-latin-ext_latin-700.eot
  assets/GLOBAL/css/titillium-web/titillium-web-v8-latin-ext_latin-700.svg
  assets/GLOBAL/css/titillium-web/titillium-web-v8-latin-ext_latin-700.ttf
  assets/GLOBAL/css/titillium-web/titillium-web-v8-latin-ext_latin-700.woff
  assets/GLOBAL/css/titillium-web/titillium-web-v8-latin-ext_latin-700.woff2
  assets/GLOBAL/css/titillium-web/titillium-web-v8-latin-ext_latin-regular.eot
  assets/GLOBAL/css/titillium-web/titillium-web-v8-latin-ext_latin-regular.svg
  assets/GLOBAL/css/titillium-web/titillium-web-v8-latin-ext_latin-regular.ttf
  assets/GLOBAL/css/titillium-web/titillium-web-v8-latin-ext_latin-regular.woff
  assets/GLOBAL/css/titillium-web/titillium-web-v8-latin-ext_latin-regular.woff2
Labels: impact:accessibility, platform:website

#87 fixed typos and rephrased a couple things
  _posts/ru/2020-09-04-ALTF4-3.md
Labels: impact:translation

#92 #91: Use * not <em> for italics in about markdown
  about.en.md
  about.ru.md
Labels: impact:documentation, platform:website

#96 Added automatic release action
  .github/workflows/Automatic_Release.yml
Labels: impact:enhancement, platform:website

#102 Added automating anchoring
  404.en.md
  404.fr.md
  404.it.md
  404.ua.md
  _includes/anchor_headings.html
  _layouts/page.html
  _layouts/post.html
  about.en.md
  about.fr.md
  about.it.md
  about.ru.md
  about.ua.md
Labels: impact:enhancement, platform:website

#103 Added alt-f4 3 it
  _posts/it/2020-09-04-ALTF4-3.md
Labels: impact:translation

#105 Change a few images to webp, 1.8 mb transferred --> 1.3 mb transferred
  _includes/head.html
  _sass/base.scss
  _sass/footer.scss
  assets/GLOBAL/img/bg.webp
  assets/GLOBAL/img/footer-bg.webp
  assets/GLOBAL/img/spider-idle.gif
  assets/GLOBAL/img/spider-idle.webp
  assets/GLOBAL/js/modernizr-webp.js
Labels: impact:enhancement, platform:website

#98 Fanart 1
  submissions/fanart1/fanart1.md
Labels: impact:submission

#54 Designing Blueprints
  submissions/designing_blueprints/designing_blueprints.md
Labels: impact:submission

#94 Mobile redesign / big improvements
  _includes/navbar.html
  _includes/youtube.html
  _sass/base.scss
  _sass/buttons.scss
  _sass/navbar.scss
  _sass/slots.scss
  assets/GLOBAL/img/mobile-bg.jpg
  assets/GLOBAL/img/mobile-bg.webp
Labels: impact:accessibility, impact:enhancement, platform:website

#108 Fixed Language Button on iOS
  _includes/navbar.html
Labels: platform:website

#122 #121: Remove unused assets
  assets/GLOBAL/css/factorio.css
  assets/GLOBAL/img/rocket-idle.png
  assets/GLOBAL/img/spider-idle_old.gif
Labels: impact:documentation, platform:website

#127 Updated header styling
  _sass/text.scss
Labels: platform:website

#126 Updated PR template with new embed standards
  .github/PULL_REQUEST_TEMPLATE.md
Labels: impact:documentation, platform:github

#148 Landfill rant
  submissions/landfill_rant/landfill_rant.md
Labels: impact:submission

#90 Factorio Zone
  submissions/FactorioZone/FactorioZone.md
Labels: impact:submission

#149 Realistic Fusion Weaponry
  submissions/realistic_fusion_weaponry/realistic_fusion_weaponry.md
Labels: impact:submission

#163 Alt-F4 - Translation push
  _data/de/locale.yml
  _posts/en/2020-09-04-ALTF4-3.md
  _posts/es/2020-09-04-ALTF4-3.md
  _posts/fr/2020-09-04-ALTF4-3.md
  _posts/it/2020-09-04-ALTF4-3.md
  _posts/ru/2020-09-04-ALTF4-3.md
Labels: impact:translation

#166 Translation push
  _posts/zh/2020-08-28-ALTF4-2.md
  _posts/zh/2020-09-04-ALTF4-3.md
Labels: impact:translation

#167 Chinese Translation - Corrections for Issue3
  _posts/zh/2020-09-04-ALTF4-3.md
Labels: impact:translation

#53 Facto-RayO v2
  submissions/FactoRayO/FactoRayO.md
Labels: impact:submission, status:copy-edited

#158 Nauvis Archives
  submissions/nauvis_archives/nauvis_archives.md
Labels: impact:submission, status:copy-edited

#159 Factorio review by MandalorianGaming channel
  submissions/factorio_review_mandaloriangaming/factorio_review_mandaloriangaming.md
Labels: impact:submission, status:copy-edited

#165 Issue Nr6
  _drafts/2020-09-25-ALTF4-6.md
  assets/ALTF4/6/thumbnail.jpg
Labels: impact:submission, status:copy-edited

#169 AltF4-6 Translation push
  _config.yml
  _posts /de /2020-09-25-ALTF4-6.md
  _posts/es/2020-09-25-ALTF4-6.md
  _posts/fr/2020-09-25-ALTF4-6.md
  _posts/it/2020-09-25-ALTF4-6.md
Labels: impact:translation

#174 Chinese Translation - Issue 6
  _posts/zh/2020-09-25-ALTF4-6.md
Labels: impact:translation

#175 Translation push
  _posts/it/2020-08-28-ALTF4-2.md
Labels: impact:translation

#173 Chinese Translation - Issue 4
  _posts/zh/2020-09-11-ALTF4-4.md
Labels: impact:translation

#172 Chinese Translation - Issue 5
  _posts/zh/2020-09-18-ALTF4-5.md
Labels: impact:translation

#178 alphabetize language switcher
  _config.yml
Labels: platform:website

#180 Spelling correction
  _posts/de/2020-09-25-ALTF4-6.md
  _posts/en/2020-09-25-ALTF4-6.md
  _posts/es/2020-09-25-ALTF4-6.md
  _posts/fr/2020-09-25-ALTF4-6.md
  _posts/it/2020-09-25-ALTF4-6.md
  _posts/zh/2020-09-25-ALTF4-6.md
Labels: impact:translation

#179 Czech translation
  _config.yml
  _data/cs/locale.yml
  _posts/cs/2020-08-21-ALTF4-1.md
  _posts/cs/2020-08-28-ALTF4-2.md
Labels: impact:translation

#164 Some new stuff
  _drafts/compare.md
  _includes/compare.html
  _includes/video.html
  _layouts/post.html
  _plugins/random.rb
  _plugins/regex_filter.rb
  _posts/en/2020-09-18-ALTF4-5.md
  _sass/media.scss
Labels: platform:website

#186 Translation push
  _posts/de/2020-09-18-ALTF4-5.md
Labels: impact:translation
