Repository AlternativeFFFF/Alt-F4, pull requests merged in 2020-11, with the labels that each got.

#272 Performance fixes
  _includes/video.html
  _posts/en/2020-10-30-ALTF4-11.md
  _posts/es/2020-10-30-ALTF4-11.md
  _posts/fr/2020-10-30-ALTF4-11.md
  _sass/text.scss
  assets/GLOBAL/js/spidertron.js
Labels: impact:accessibility

#276 DE Miscellaneous fixes
  _data/de/locale.yml
  _posts/de/2020-10-02-ALTF4-7.md
  _posts/de/2020-10-09-ALTF4-8.md
  _posts/de/2020-10-16-ALTF4-9.md
Labels: impact:translation

#278 Issue 11 - IT
  _posts/it/2020-10-30-ALTF4-11.md
Labels: impact:translation

#281 Issue 12
  _drafts/2020-11-06-ALTF4-12.md
  assets/ALTF4/12/thumbnail.jpg
Labels: impact:submission, status:reviewed

#250 Building Spidertron submission
  submissions/building_spidertron/building_spidertron.md
Labels: impact:submission, status:reviewed

#277 Complexity Corner - Productivity modules
  submissions/prod_modules/Complexity Corner 1 - Productivity Modules.md
Labels: impact:submission, status:reviewed

#279 @Tarsassum AltF4E11Tar Comfy/BCG Teamup MMO
  submissions/AltF4-11ComfyParty-3/Tar11ComfyParty_3.md
Labels: impact:submission, status:reviewed

#282 Chinese Translation - Issue 12
  _posts/zh/2020-11-06-ALTF4-12.md
Labels: impact:translation

#283 Issue 12 - Translation push
  _posts/de/2020-10-30-ALTF4-12.md
  _posts/fr/2020-10-30-ALTF4-12.md
Labels: impact:translation

#286 next post prev post buttons
  _layouts/page.html
  _sass/base.scss
Labels: platform:website

#287 Native quote transltalion supprt
  _includes/quote.html
  _posts/de/2020-10-23-ALTF4-10.md
  _posts/de/2020-11-06-ALTF4-12.md
  _posts/es/2020-10-23-ALTF4-10.md
  _posts/fr/2020-10-23-ALTF4-10.md
  _posts/fr/2020-11-06-ALTF4-12.md
  _posts/it/2020-10-23-ALTF4-10.md
  _posts/nl/2020-10-23-ALTF4-10.md
  _posts/ru/2020-10-23-ALTF4-10.md
  _posts/zh/2020-10-23-ALTF4-10.md
  _posts/zh/2020-11-06-ALTF4-12.md
Labels: platform:website

#288 Whole card is a link
  _layouts/home.html
  _sass/panel.scss
Labels: platform:website

#292 Prepare issue 13
  _drafts/2020-11-13-Alt-F4-13.md
  assets/ALTF4/13/thumbnail.jpg
Labels: impact:submission, status:reviewed

#291 Credit tweaks + layout updates
  _includes/author.html
  _layouts/home.html
  _layouts/page.html
Labels: impact:enhancement, platform:website

#280 Nauvis Archives: One Rocket Defense Per Minute
  submissions/nauvis_archives_ancient_megabase/nauvis_archives_ancient_megabase.md
Labels: impact:submission, status:reviewed

#293 Issue 13 - Translation push
  _posts/de/2020-11-13-ALTF4-13.md
  _posts/fr/2020-11-13-ALTF4-13.md
Labels: impact:translation

#290 Update spidertron (performance fixes)
  _sass/base.scss
  assets/GLOBAL/css/spidertron.css
  assets/GLOBAL/js/spidertron.js
Labels: impact:bug, platform:website

#306 Adjusting footer buttons
  _sass/slots.scss
Labels: platform:website

#295 initial buttons.scss refactoring
  _sass/buttons.scss
Labels: impact:enhancement, platform:website

#310 PR Review Notify
  .github/workflows/PR_Review_Notify.yml
Labels: impact:enhancement, platform:github

#309 Fix body height on short pages
  _sass/base.scss
Labels: impact:bug, platform:website

#312 Added .active
  _sass/buttons.scss
Labels: platform:website

#305 Generic image include
  _includes/image.html
  _sass/image.scss
  assets/GLOBAL/css/style.scss
Labels: impact:enhancement, platform:website

#302 Space exploration Mod Spotlight
  submissions/space_exploration/space-exploration-mod-spotlight.md
Labels: impact:submission, status:reviewed

#313 Issue 14
  _drafts/2020-11-20-ALTF4-14.md
  assets/ALTF4/14/thumbnail.jpg
Labels: impact:submission, status:reviewed

#316 Issue14 - Translation push
  _posts/de/2020-11-20-ALTF4-14.md
  _posts/es/2020-11-20-ALTF4-14.md
  _posts/fr/2020-11-20-ALTF4-14.md
Labels: impact:translation

#314 Chinese Translation - Issue 14
  _posts/zh/2020-11-20-ALTF4-14.md
Labels: impact:translation

#315 CS - Issue 3
  _posts/cs/2020-09-04-ALTF4-3.md
Labels: impact:translation

#321 Support for mobile version of image in image embed
  _drafts/2020-08-20-ALTF4-X.md
  _includes/image.html
  _sass/base.scss
  _sass/image.scss
Labels: impact:enhancement, platform:website

#319 Issue 15
  _drafts/2020-11-27-ALTF4-15.md
  assets/ALTF4/15/thumbnail.jpg
Labels: impact:submission, status:reviewed

#318 1.1 Performance Improvements
  submissions/11_performance/11_performance.md
Labels: impact:submission, status:reviewed

#317 1.1 Feature Discussion - Train stop limits
  submissions/train-stop-limits/train-stop-limits.md
Labels: impact:submission, status:reviewed

#323 Issue 15 - Translation push
  _posts/de/2020-11-27-ALTF4-15.md
  _posts/es/2020-11-27-ALTF4-15.md
  _posts/fr/2020-11-27-ALTF4-15.md
Labels: impact:translation

#322 Fix spidertron leg lengths
  assets/GLOBAL/css/spidertron.css
Labels: impact:bug, platform:website

#329 Issues on Issue 15 - FR
  _posts/fr/2020-11-27-ALTF4-15.md
Labels: impact:translation

#328 #289: Add locale support to countdowns (and small refactoring)
  _data/cs/locale.yml
  _data/de/locale.yml
  _data/en/locale.yml
  _data/es/locale.yml
  _data/fr/locale.yml
  _data/nl/locale.yml
  _data/ru/locale.yml
  _data/ua/locale.yml
  _data/zh/locale.yml
  _drafts/2020-08-20-ALTF4-X.md
  _includes/countdown.html
  _sass/countdown.scss
Labels: impact:translation, platform:website
