Repository AlternativeFFFF/Alt-F4, pull requests merged in 2020-12, with the labels that each got.

#332 Issue 16
  _drafts/2020-12-04-ALTF4-16.md
  assets/ALTF4/16/thumbnail.jpg
Labels: impact:submission, status:reviewed

#331 Complexity Corner 2: Speed Modules
  submissions/complexity_corner_speed_modules/complexity_corner_speed_modules.md
Labels: impact:submission, status:reviewed

#298 Modding Inspiration
  submissions/modding_inspiration/modding_inspiration.md
Labels: impact:submission, status:reviewed

#334 Issue 16 - Translation push
  _posts/fr/2020-12-04-ALTF4-16.md
Labels: impact:translation

#333 Chinese Translation - Issue 16
  _posts/zh/2020-12-04-ALTF4-16.md
Labels: impact:translation

#338 excerpt first paragraph
  Gemfile
  _layouts/home.html
  _plugins/first_paragraph.rb
Labels: impact:enhancement, platform:website

#330 Submissions relabeled discord notifications
  .github/workflows/PR_Labeled_Notify.yml
Labels: platform:discord, platform:github

#336 Optimising CountDown include
  _includes/countdown.html
Labels: impact:enhancement, platform:website

#337 Adding possibility to translate fullres text in Image include
  _data/cs/locale.yml
  _data/de/locale.yml
  _data/en/locale.yml
  _data/es/locale.yml
  _data/fr/locale.yml
  _data/it/locale.yml
  _data/nl/locale.yml
  _data/pl/locale.yml
  _data/ru/locale.yml
  _data/ua/locale.yml
  _data/zh/locale.yml
  _includes/image.html
Labels: impact:enhancement, platform:website

#344 Centered countdown embed
  _includes/countdown.html
Labels: platform:website

#345 Vertical Quote
  _includes/quote.html
  _sass/quote.scss
Labels: platform:website

#341 Issue 17
  _drafts/2020-12-11-ALTF4-17.md
  assets/ALTF4/17/thumbnail.jpg
Labels: Ready, impact:submission

#339 Interface Design Considerations
  submissions/design_consideration/design_consideration.md
Labels: Ready, impact:submission

#340 Santa Factory - Red Circuit
  submissions/santa_factory/santa_factory.md
Labels: Ready, impact:submission

#347 Some Bird Has Saved The Day
  _includes/quote.html
  _sass/quote.scss
Labels: platform:website

#346 Issue 17 - Translation push
  _posts/de/2020-12-11-ALTF4-17.md
  _posts/es/2020-12-11-ALTF4-17.md
  _posts/fr/2020-12-11-ALTF4-17.md
Labels: impact:translation

#349 Issue 18
  _drafts/2020-12-18-ALTF4-18.md
  assets/ALTF4/18/thumbnail.jpg
Labels: Technical-Review, impact:submission

#326 Road to Clusterio #1
  submissions/hornwitser_clusterio_v2/road-to-clusterio-2.0.md
Labels: Ready, impact:submission

#297 Moddability - The Birth of a Mod
  submissions/moddability__the_birth_of_a_mod/moddability__the_birth_of_a_mod.md
Labels: Ready, impact:submission

#352 Issue 18 - Translation Push
  _posts/de/2020-12-18-ALTF4-18.md
  _posts/es/2020-12-18-ALTF4-18.md
  _posts/fr/2020-12-18-ALTF4-18.md
Labels: impact:translation

#354 Chinese Translation - Issue 17 & 18
  _posts/zh/2020-12-11-ALTF4-17.md
  _posts/zh/2020-12-18-ALTF4-18.md
Labels: impact:translation
