Repository AlternativeFFFF/Alt-F4, pull requests merged in 2021-06, with the labels that each got.

#503 Issue 38
  _drafts/2021-06-04-ALTF4-38.md
  assets/ALTF4/38/thumbnail.jpg
Labels: Ready, impact:submission

#492 Factorio and STEM
  submissions/career/career.md
Labels: Ready, impact:submission

#505 Issue 38 - Translation push
  _posts/fr/2021-06-04-ALTF4-38.md
Labels: impact:translation

#506 Issue 38 - DE Translations
  _posts/de/2021-06-04-ALTF4-38.md
Labels: impact:translation

#504 Issue 38 - Chinese Translation
  _posts/zh/2021-06-04-ALTF4-38.md
Labels: impact:translation

#475 added gallery
  _includes/gallery.html
  _sass/media.scss
Labels: impact:enhancement, platform:website

#509 Issue 39
  _drafts/2021-06-11-ALTF4-39.md
  assets/ALTF4/39/thumbnail.jpg
Labels: New, impact:submission

#498 JOSEF
  _drafts/JOSEF.md
Labels: Ready, impact:submission

#510 Issue 39 - Translations
  _posts/de/2021-06-11-ALTF4-39.md
  _posts/fr/2021-06-11-ALTF4-39.md
Labels: impact:translation

#514 Twitch clip
  _includes/twitch.html
  _sass/media.scss
Labels: impact:enhancement, platform:website
