Repository AlternativeFFFF/Alt-F4, pull requests merged in 2021-01, with the labels that each got.

#355 Issue 19 - Retrospective
  _posts/de/2021-01-01-ALTF4-19.md
  _posts/en/2021-01-01-ALTF4-19.md
  assets/ALTF4/19/thumbnail.jpg
Labels: Ready, impact:submission, status:new

#357 ALTF4-19: french translation
  _posts/fr/2021-01-01-ALTF4-19.md
Labels: impact:translation

#361 DE #19 corrections
  _posts/de/2021-01-01-ALTF4-19.md
Labels: impact:translation

#360 Issue 20
  _drafts/2021-01-08-ALTF4-20.md
  assets/ALTF4/20/thumbnail.jpg
Labels: Editing, impact:submission, status:new

#364 Issue20 - Translation push
  _config.yml
  _data/pt-br/locale.yml
  _posts/de/2021-01-08-ALTF4-20.md
  _posts/fr/2021-01-08-ALTF4-20.md
  _posts/pt-br/2021-01-08-ALTF4-20.md
Labels: impact:translation

#362 Chinese Translation - Issue 20
  _posts/zh/2021-01-08-ALTF4-20.md
Labels: impact:translation

#365 [DE] Fixed link localization
  _posts/de/2021-01-08-ALTF4-20.md
Labels: impact:translation

#366 Issue 20 - FR fix
  _posts/fr/2021-01-08-ALTF4-20.md
Labels: impact:translation

#367 PT-BR - Transcription update
  _posts/pt-br/2021-01-08-ALTF4-20.md
Labels: impact:translation

#368 don't load mobile bg when loading normal bg
  _sass/base.scss
Labels: platform:website

#371 Issue 21
  _drafts/2021-01-15-ALTF4-21.md
  assets/ALTF4/21/thumbnail.jpg
Labels: Ready, impact:submission

#369 Nauvis Archives: From Mod to Vanilla
  submissions/nauvis_archives_mod_to_vanilla/nauvis_archives_mod_to_vanilla.md
Labels: Ready, impact:submission

#370 Reader polls
  submissions/user-poll/user-poll.md
Labels: Ready, impact:submission

#372 Updated locale for Czech
  _data/cs/locale.yml
Labels: impact:translation

#375 Issue21 - translation push
  _posts/de/2021-01-15-ALTF4-21.md
  _posts/fr/2021-01-15-ALTF4-21.md
  _posts/pt-br/2021-01-15-ALTF4-21.md
  _posts/zh/2021-01-15-ALTF4-21.md
Labels: impact:translation

#374 CS/CZ Translation of #21
  _posts/cs/2021-01-15-ALTF4-21.md
Labels: impact:translation

#376 Bug/locale - Fixing Czech locale
  _data/cs/locale.yml
Labels: impact:translation

#378 PT-BR - Grammar and others fixes
  _posts/pt-br/2021-01-15-ALTF4-21.md
Labels: impact:translation

#381 Issue 22
  _drafts/2021-01-22-ALTF4-22.md
  _posts/en/2021-01-01-ALTF4-19.md
  _posts/en/2021-01-08-ALTF4-20.md
  _posts/en/2021-01-15-ALTF4-21.md
  assets/ALTF4/22/thumbnail.jpg
Labels: Ready, impact:submission, status:edited

#379 Blueprint rant
  submissions/blueprint-rant/blueprint-rant.md
Labels: Ready, impact:submission

#385 Issue 22 - Translation push
  _posts/de/2021-01-22_ALTF4-22.md
  _posts/fr/2021-01-22-ALTF4-22.md
Labels: impact:translation

#383 Issue 22 - CS Translation
  _posts/cs/2021-01-22-ALTF4-22.md
Labels: impact:translation

#384 Issue 22 - PT-BR Translation
  _posts/pt-br/2021-01-22-ALTF4-22.md
Labels: impact:translation

#386 Issue 22 - Chinese Translation
  _posts/zh/2021-01-22-ALTF4-22.md
Labels: impact:translation

#387 Standard FR numerotation way
  _posts/fr/2020-08-21-ALTF4-1.md
  _posts/fr/2020-08-28-ALTF4-2.md
  _posts/fr/2020-09-04-ALTF4-3.md
  _posts/fr/2020-09-11-ALTF4-4.md
  _posts/fr/2020-09-18-ALTF4-5.md
  _posts/fr/2020-09-25-ALTF4-6.md
  _posts/fr/2020-10-02-ALTF4-7.md
  _posts/fr/2020-10-09-ALTF4-8.md
  _posts/fr/2020-10-16-ALTF4-9.md
  _posts/fr/2020-10-23-ALTF4-10.md
  _posts/fr/2020-10-30-ALTF4-11.md
  _posts/fr/2020-11-06-ALTF4-12.md
  _posts/fr/2020-11-13-ALTF4-13.md
  _posts/fr/2020-11-20-ALTF4-14.md
  _posts/fr/2020-11-27-ALTF4-15.md
  _posts/fr/2020-12-04-ALTF4-16.md
  _posts/fr/2020-12-11-ALTF4-17.md
  _posts/fr/2020-12-18-ALTF4-18.md
  _posts/fr/2021-01-01-ALTF4-19.md
  _posts/fr/2021-01-08-ALTF4-20.md
Labels: impact:translation

#393 [DE] Minor corrections to Issue 22
  _posts/de/2021-01-22-ALTF4-22.md
Labels: impact:translation

#392 Issue #9 Editors Note - Chinese Translation
  _posts/zh/2020-10-16-ALTF4-9.md
Labels: impact:translation

#390 Changed cursor to pinter when hover over toc
  _sass/toc.scss
Labels: impact:enhancement, platform:website

#382 Nauvis Archives: Issue #9 Editors Note
  _posts/de/2020-10-16-ALTF4-9.md
  _posts/en/2020-10-16-ALTF4-9.md
  _posts/es/2020-10-16-ALTF4-9.md
  _posts/fr/2020-10-16-ALTF4-9.md
  _posts/it/2020-10-16-ALTF4-9.md
Labels: impact:translation

#394 Chinese proofreading for 1-22
  _posts/zh/2020-08-21-ALTF4-1.md
  _posts/zh/2020-08-28-ALTF4-2.md
  _posts/zh/2020-09-04-ALTF4-3.md
  _posts/zh/2020-09-11-ALTF4-4.md
  _posts/zh/2020-09-18-ALTF4-5.md
  _posts/zh/2020-09-25-ALTF4-6.md
  _posts/zh/2020-10-02-ALTF4-7.md
  _posts/zh/2020-10-09-ALTF4-8.md
  _posts/zh/2020-10-16-ALTF4-9.md
  _posts/zh/2020-10-23-ALTF4-10.md
  _posts/zh/2020-10-30-ALTF4-11.md
  _posts/zh/2020-11-06-ALTF4-12.md
  _posts/zh/2020-11-13-ALTF4-13.md
  _posts/zh/2020-11-20-ALTF4-14.md
  _posts/zh/2020-11-27-ALTF4-15.md
  _posts/zh/2020-12-04-ALTF4-16.md
  _posts/zh/2020-12-11-ALTF4-17.md
  _posts/zh/2020-12-18-ALTF4-18.md
  _posts/zh/2021-01-01-ALTF4-19.md
  _posts/zh/2021-01-08-ALTF4-20.md
  _posts/zh/2021-01-15-ALTF4-21.md
  _posts/zh/2021-01-22-ALTF4-22.md
Labels: impact:translation
