Repository AlternativeFFFF/Alt-F4, pull requests merged in 2021-08, with the labels that each got.

#541 Issue 45
  _drafts/2021-08-06-ALTF4-45.md
  assets/ALTF4/45/thumbnail.jpg
Labels: impact:submission, New

#534 Satisfactorio!
  _drafts/satisfactorio.md
Labels: impact:submission, Editing

#542 Issue 45 - Translation Push
  _posts/fr/2021-08-06-ALTF4-45.md
  _posts/ru/2021-08-06-ALTF4-45.md
  _posts/zh/2021-08-06-ALTF4-45.md
Labels: impact:translation

#546 Issue 46
  _drafts/2021-08-20-ALTF4-46.md
  assets/ALTF4/46/thumbnail.jpg
Labels: impact:submission, New

#544 One Year of Alt-F4
  _drafts/one-year.md
  _sass/flex.scss
Labels: impact:submission, New

#548 Issue 46 - Translation Push
  _posts/fr/2021-08-20-ALTF4-46.md
Labels: impact:translation

#547 Issue 46 - Chinese Translation
  _posts/zh/2021-08-20-ALTF4-46.md
Labels: impact:translation
