Repository AlternativeFFFF/Alt-F4, pull requests merged in 2021-03, with the labels that each got.

#420 Issue 26
  _drafts/2021-03-05-ALTF4-26.md
  assets/ALTF4/26/thumbnail.jpg
Labels: New, impact:submission

#388 Factorio: Deterministic Multiplayer
  submissions/servers/servers.md
Labels: Translation, impact:submission

#422 Issue 26 - Translation push
  _posts/de/2021-03-05_ALTF4-26.md
  _posts/fr/2021-03-04-ALTF4-26.md
Labels: impact:translation

#421 Issue 26 - Chinese Translation
  _posts/zh/2021-03-05-ALTF4-26.md
Labels: impact:translation

#423 Issue 26 - CS Translation
  _posts/cs/2021-03-04-ALTF4-26.md
Labels: impact:translation

#425 Issue 27
  _drafts/2021-03-12-ALTF4-27.md
  assets/ALTF4/27/thumbnail.jpg
Labels: New, impact:submission

#415 Universal 8-8 - Balancer design
  submissions/balancer-design/universal_8to8.md
Labels: Ready, impact:submission

#427 Issue 27 - Translation push
  _posts/de/2021-03-12-ALTF4-27.md
  _posts/fr/2021-03-12-ALTF4-27.md
Labels: impact:translation

#428 Issue 27 - CS Translation
  _posts/cs/2021-03-12-ALTF4-27.md
Labels: impact:translation

#426 Issue 27 - Chinese Translation
  _posts/zh/2021-03-12-ALTF4-27.md
Labels: impact:translation

#430 Issue 28
  _drafts/2021-03-19-ALTF4-28.md
  assets/ALTF4/28/thumbnail.jpg
Labels: Ready, impact:submission

#395 Recipe-Oriented Factorio Life
  _includes/map.html
  _sass/aspect.scss
  assets/GLOBAL/css/style.scss
  submissions/recipe_oriented_factorio_life/recipe_oriented_factorio_life.md
Labels: Ready, impact:submission

#432 Issue 28 - Translation Push
  _posts/de/2021-03-19-ALTF4-28.md
  _posts/fr/2021-03-19-ALTF4-28.md
Labels: impact:translation

#431 Issue 28 - CS Translation
  _posts/cs/2021-03-19-ALTF4-28.md
Labels: impact:translation

#433 Issue 28 - Chinese Translation
  _posts/zh/2021-03-19-ALTF4-28.md
Labels: impact:translation

#434 add newsletter icon to footer
  _includes/footer.html
Labels: impact:enhancement, platform:website

#402 remove modernizr-webp.js
  _includes/head.html
Labels: platform:website

#439 Issue 29
  _drafts/2021-03-26-ALTF4-29.md
  assets/ALTF4/29/thumbnail.jpg
Labels: New, impact:submission

#429 Complexity Corner 4
  submissions/Complexity Corner 4/Complexity Corner 4.md
Labels: Translation, impact:submission

#438 Factorio Mod Spotlight: No Belts
  submissions/no-belts/main.md
Labels: impact:submission

#441 Issue 29 - CS translation
  _posts/cs/2021-03-26-ALTF4-29.md
Labels: impact:translation

#442 Alt-F4 29 Translation push
  _posts/de/2021-03-26-ALTF4-29.md
  _posts/fr/2021-03-26-ALTF4-29.md
Labels: impact:translation

#440 Issue 29 - Chinese Translation
  _posts/zh/2021-03-26-ALTF4-29.md
Labels: impact:translation
