Repository AlternativeFFFF/Alt-F4, pull requests merged in 2021-11, with the labels that each got.

#577 Issue 51
  _drafts/2021-11-05-ALTF4-51.md
  assets/ALTF4/51/thumbnail.jpg
Labels: impact:submission, New

#567 The Fluidic Power Experiment
  _drafts/fluidic-power.md
Labels: impact:submission, New

#578 Issue 51 - CS translation
  _posts/cs/2021-11-05-ALTF4-51.md
Labels: impact:translation

#579 Issue 51 - Chinese Translation
  _posts/zh/2021-11-05-ALTF4-51.md
Labels: impact:translation

#580 Issue51 - Translation push
  _posts/fr/2021-10-29-ALTF4-50.md
  _posts/fr/2021-11-05-ALTF4-51.md
Labels: impact:translation

#583 Issue 52
  _drafts/2021-11-12-ALTF4-52.md
Labels: impact:submission, New

#576 The Fluidic Power Experiment: Part 2
  _drafts/fluidic-power.md
Labels: impact:submission, Technical-Review

#589 Issue 53
  _drafts/2021-11-26-ALTF4-53.md
  assets/ALTF4/53/thumbnail.jpg
Labels: impact:submission, Ready

#586 Laziness through automation
  _drafts/screenshotter.md
Labels: impact:submission, Ready

#593 Issue 53 - Translation push
  _posts/de/2021-11-26-ALTF4-53.md
  _posts/fr/2021-11-26-ALTF4-53.md
Labels: impact:translation

#591 Issue 53 - CS Translation
  _posts/cs/2021-11-26-ALTF4-53.md
Labels: impact:translation

#590 Issue 53 - Chinese Translation
  _posts/zh/2021-11-26-ALTF4-53.md
Labels: impact:translation
