Repository AlternativeFFFF/Alt-F4, pull requests merged in 2021-09, with the labels that each got.

#545 Optimizing the solution
  _drafts/optimizing-the-solution.md
  _includes/image.html
  _sass/image.scss
Labels: impact:submission, Ready

#552 Issue 47
  _drafts/2021-09-17-ALTF4-47.md
  assets/ALTF4/47/thumbnail.jpg
Labels: impact:submission, Ready

#553 Issue 47 - Translation push
  _posts/de/2021-07-16-ALTF4-42.md
  _posts/de/2021-08-20-ALTF4-46.md
  _posts/de/2021-09-17-ALTF4-47.md
  _posts/fr/2021-09-17-ALTF4-47.md
Labels: impact:translation

#555 Issue 47 - Chinese Translation
  _posts/zh/2021-09-17-ALTF4-47.md
Labels: impact:translation

#551 Angel's unit tests
  _drafts/angels_unit_tests.md
Labels: impact:submission, Ready

#557 Issue 48
  _drafts/2021-09-24-ALTF4-48.md
  assets/ALTF4/48/thumbnail.jpg
Labels: impact:submission, Ready

#558 Issue 48 - Translation push
  _posts/fr/2021-09-24-ALTF4-48.md
Labels: impact:translation

#559 Issue 48 - Chinese Translation
  _posts/zh/2021-09-24-ALTF4-48.md
Labels: impact:translation

#556 First matrix fix
  _posts/de/2021-09-17-ALTF4-47.md
  _posts/en/2021-09-17-ALTF4-47.md
  _posts/fr/2021-09-17-ALTF4-47.md
  _posts/zh/2021-09-17-ALTF4-47.md
Labels: impact:submission
