Repository AlternativeFFFF/Alt-F4, pull requests merged in 2021-12, with the labels that each got.

#596 Issue 54 - CS tranlsation
  _posts/cs/2021-12-10-ALTF4-54.md
Labels: impact:translation

#594 Issue 5 - RU translation
  _posts/ru/2020-09-18-ALTF4-5.md
Labels: impact:translation

#588 add semicolon
  assets/GLOBAL/js/spidertron.js
Labels: impact:enhancement

#597 Issue 54 - Chinese Translation
  _posts/zh/2021-12-10-ALTF4-54.md
Labels: impact:translation

#599 Issue 55
  _drafts/2021-12-17-ALTF4-55.md
  assets/ALTF4/55/thumbnail.jpg
Labels: impact:submission, New

#598 Modding Behind the Scenes
  _drafts/modding-behind-the-scenes.md
Labels: impact:submission, New

#600 Issue #55 Translations
  _posts/de/2021-12-17-ALTF4-55.md
  _posts/fr/2021-12-17-ALTF4-55.md
Labels: impact:translation

#601 Issue 55 - Chinese Translation
  _posts/zh/2021-12-17-ALTF4-55.md
Labels: impact:translation

#602 End of 2021
  _drafts/end-2021.md
  assets/ALTF4/56/thumbnail.jpg
Labels: impact:submission, New

#604 Issue #56 - Translations
  _posts/de/2021-12-31-ALTF4-56.md
  _posts/fr/2021-12-31-ALTF4-56.md
Labels: impact:translation
