Repository AlternativeFFFF/Alt-F4, pull requests merged in 2021-05, with the labels that each got.

#480 Reddit action fix
  .github/workflows/Release_Notify.yml
Labels: platform:github

#481 Issue 34
  _drafts/2021-05-07-ALTF4-34.md
  assets/ALTF4/34/thumbnail.jpg
Labels: Ready, impact:submission

#473 Best of its genre - Factorio Origins
  submissions/best-of-its-genre-nanogamer7/origins.md
Labels: Ready, impact:submission

#483 Issue 34 Translations
  _posts/de/2021-05-07-ALTF4-34.md
  _posts/fr/2021-05-07-ALTF4-34.md
Labels: impact:translation

#482 Issue 34 - Chinese Translation
  _posts/zh/2021-05-07-ALTF4-34.md
Labels: impact:translation

#487 Issue 35
  _drafts/2021-05-14-ALTF4-35.md
  assets/ALTF4/35/thumbnail.jpg
Labels: New, impact:submission

#471 The Engineer's Physics-Defying Strength
  submissions/engineers-physics/The_Engineers_Physics-Defying_Strength.md
Labels: Ready, impact:submission

#484 Mod Spotlight: Hall of Fame
  submissions/hall-of-fame/hall-of-fame.md
Labels: Ready, impact:submission

#489 Issue 35 - CS Translation
  _posts/cs/2021-05-14-ALTF4-35.md
Labels: impact:translation

#488 Issue 35 - Chinese Translation
  _posts/zh/2021-05-14-ALTF4-35.md
Labels: impact:translation

#491 Issue 35 - Translation push
  _posts/de/2021-05-14_ALTF4-35.md
  _posts/fr/2021-05-13-ALTF4-35.md
Labels: impact:translation

#494 Issue 36
  _drafts/2021-05-21-ALTF4-36.md
  assets/ALTF4/36/thumbail.jpg
Labels: New, impact:submission

#486 Nauvian Perspective: Bentham and Xisumavoid
  submissions/nauvian-perspective-bentham/nauvian-perspective-bentham.md
Labels: Ready, impact:submission

#495 Issue 36 - Translation push
  _posts/fr/2021-05-21-ALTF4-36.md
Labels: impact:translation

#496 Issue 36 - Chinese Translation
  _posts/zh/2021-05-21-ALTF4-36.md
Labels: impact:translation

#497 Issue 36 - DE Translation
  _posts/de/2021-05-21-ALTF4-36.md
Labels: impact:translation

#500 Issue 37
  _drafts/2021-05-28-37.md
  assets/ALTF4/37/thumbnail.jpg
Labels: Ready, impact:submission

#499 Combinators 2: Augmented Logistics
  submissions/combinators-2/combinators-2.md
Labels: Ready, impact:submission

#502 Issue 37 - Chinese Translation
  _posts/zh/2021-05-28-ALTF4-37.md
Labels: impact:translation
