Repository AlternativeFFFF/Alt-F4, pull requests merged in 2021-04, with the labels that each got.

#446 TTT 30 - Chinese Translation
  _posts/zh/2021-04-01-TTT-30.md
Labels: impact:translation

#444 Issue 30
  _drafts/2021-04-02-ALTF4-30.md
  assets/ALTF4/30/thumbail.jpg
Labels: Ready, impact:submission

#437 The Nauvian Perspective: Zisteau
  submissions/zisteau_interview/zisteau_interview.md
Labels: Ready, impact:submission

#448 Issue30 - Translation push
  _posts/cs/2021-04-02-ALTF4-30.md
  _posts/de/2021-04-02-ALTF-30.md
  _posts/fr/2021-04-02-ALTF4-30.md
Labels: impact:translation

#445 Issue 30 - Chinese Translation
  _posts/zh/2021-04-02-ALTF4-30.md
Labels: impact:translation

#443 Add thumbnail to post page
  _layouts/post.html
  _sass/toc.scss
Labels: impact:enhancement, platform:website

#412 Small SEO improvements
  _includes/head.html
Labels: platform:website

#456 Issue 31
  _drafts/2021-04-16-ALTF4-31.md
  assets/ALTF4/31/thumbnail.jpg
Labels: Ready, impact:submission

#453 Pocarski - Combinators
  submissions/pocarski-combinators/pocarski-combinators.md
Labels: Ready, impact:submission

#454 Short invitation to upcoming BCG event
  submissions/BCG-IR2/BCG-IR2.md
Labels: Ready, impact:submission

#451 hacking the pagination
  _includes/pagination.html
Labels: impact:bug, platform:website

#457 Issue 31 - Chinese Translation
  _posts/zh/2021-04-16-ALTF4-31.md
Labels: impact:translation

#458 Issue 31 DE corrections
  _posts/de/2021-04-16-ALTF4-31.md
Labels: impact:translation

#462 Complexity Corner: Speakers
  submissions/Complexity Corner - Speakers/Complexity Corner - Speakers.md
Labels: Ready, impact:submission

#452 Wireshark Dissector
  submissions/hornwitser_dissector/wireshark-dissector.md
Labels: Ready, impact:submission

#467 Issue 32 - CS Translation
  _posts/cs/2021-04-23-ALTF4-32.md
Labels: impact:translation

#466 Issue 32 - Chinese Translation
  _posts/zh/2021-04-23-ALTF4-32.md
Labels: impact:translation

#469 Issue 32 - DE Translation
  _posts/de/2021-04-23-ALTF4-32.md
Labels: impact:translation

#468 Issue32 - Translation push
  _posts/fr/2021-04-23-ALTF4-32.md
Labels: impact:translation

#472 Issue 33
  _drafts/2021-04-30-ALTF4-33.md
  assets/ALTF4/33/thumbnail.jpg
Labels: Ready, impact:submission

#455 Vanilla, shaken, not stirred.
  submissions/mod-spotlight-villfuk02-randomizer/mod-spotlight-villfuk02-randomizer.md
Labels: Ready, impact:submission

#470 COMFY Minesweeper event announcement
  submissions/comfy-minesweeper/comfy-minesweeper.md
Labels: Ready, impact:submission

#478 Issue 33 - CS Translation
  _posts/cs/2021-04-23-ALTF4-32.md
  _posts/cs/2021-04-30-ALTF4-33.md
Labels: impact:translation

#477 Issue 33 - DE Translation
  _posts/de/2021-04-30-ALTF4-33.md
Labels: impact:translation

#474 Issue 33 - Chinese Translation
  _posts/zh/2021-04-30-ALTF4-33.md
Labels: impact:translation

#476 Issue 33 - Translation push
  _posts/fr/2021-04-30-ALTF4-33.md
Labels: impact:translation
