Repository AlternativeFFFF/Alt-F4, pull requests merged in 2021-02, with the labels that each got.

#389 Added possibility to name languages
  _data/cs/locale.yml
  _data/de/locale.yml
  _data/en/locale.yml
  _data/es/locale.yml
  _data/fr/locale.yml
  _data/it/locale.yml
  _data/nl/locale.yml
  _data/pl/locale.yml
  _data/pt-br/locale.yml
  _data/ru/locale.yml
  _data/ua/locale.yml
  _data/zh/locale.yml
  _includes/navbar.html
  _sass/dropdown.scss
  _sass/navbar.scss
Labels: impact:enhancement, platform:website

#400 Issue 23
  _drafts/2021-02-12-ALTF4-23.md
  assets/ALTF4/23/thumbnail.jpg
Labels: New, impact:submission

#391 Logistic Belts
  submissions/logistics_belts/logistics-belts.md
Labels: Translation, impact:submission

#396 Belt Computers Part 1
  submissions/belt-computer-part-1/belt_computer_part_1.md
Labels: Translation, impact:submission

#398 Added tables
  _config.yml
  _sass/base.scss
Labels: impact:enhancement, platform:website

#404 Issue 23 - Translation push
  _posts/de/2021-02-12-ALTF4-23.md
  _posts/fr/2021-02-12-ALTF4-23.md
Labels: impact:translation

#399 Issue 23 - CS Translation
  _posts/cs/2021-02-12-ALTF4-23.md
Labels: impact:translation

#403 Issue 23 - PT-BR Translation
  _posts/pt-br/2021-02-12-ALTF4-23.md
Labels: impact:translation

#401 Issue 23 - Chinese Translation
  _posts/zh/2021-02-12-ALTF4-23.md
Labels: impact:translation

#407 Issue 24
  _drafts/2021-02-19-ALTF4-24.md
  assets/ALTF4/24/thumbnail.jpg
Labels: New, impact:submission

#406 Belt Computers Part 2
  submissions/belt-computer-part-2/belt_computer_part_2.md
Labels: Editing, impact:submission

#410 Issue 24 - Czech translation
  _posts/cs/2021-02-19-ALTF4-24.md
Labels: impact:translation

#409 Issue 24 - Chinese Translation
  _posts/zh/2021-02-19-ALTF4-24.md
Labels: impact:translation

#408 Issue 24 - Translation push
  _posts/de/2021-02-19-ALTF4-24.md
  _posts/fr/2021-02-19-ALTF4-24.md
Labels: impact:translation

#411 Alt-f4-24 - PT-BR
  _posts/pt-br/2021-02-19-ALTF4-24.md
Labels: impact:translation

#413 Completely remove Google Analytics
  _config.yml
  _includes/analytics.html
  _includes/head.html
Labels: platform:website

#416 Issue 25
  _drafts/2021-02-26-ALTF4-25.md
  assets/ALTF4/25/thumbnail.jpg
Labels: New, impact:submission

#380 Create Complexity Corner 3 - Efficiency Modules
  submissions/Complexity Corner 3 - Efficiency Modules/Complexity Corner 3 - Efficiency Modules.md
Labels: New, impact:submission

#418 Alt F4 25 - Translation Push
  _posts/de/2021-02-26-ALTF4-25.md
  _posts/fr/2021-02-26-ALTF4-25.md
  _posts/ru/2021-02-26-ALTF4-25.md
Labels: impact:translation

#419 Issue 25 - CS Translation
  _posts/cs/2021-02-26-ALTF4-25.md
Labels: impact:translation

#417 Issue 25 - Chinese Translation
  _posts/zh/2021-02-26-ALTF4-25.md
Labels: impact:translation
