Repository AlternativeFFFF/Alt-F4, pull requests merged in 2021-07, with the labels that each got.

#515 Issue 40
  _drafts/2021-07-02-ALTF4-40.md
  assets/ALTF4/40/thumbnail.jpg
Labels: New, impact:submission

#512 Nauvian Perspective: Franqly
  _drafts/franqly.md
Labels: Ready, impact:submission

#516 Issue 40 - Chinese Translation
  _posts/zh/2021-07-02-ALTF4-40.md
Labels: impact:translation

#517 Issue 40 - Translation push
  _posts/fr/2021-07-02-ALTF4-40.md
Labels: impact:translation

#518 Issue 40 - DE Translation
  _posts/de/2021-07-01-ALTF4-40.md
Labels: impact:translation

#520 Issue 41
  _drafts/2021-07-09-ALTF4-41.md
  assets/ALTF4/41/thumbnail.jpg
Labels: Ready, impact:submission

#513 Quick Performance Check
  _drafts/QuickPerformance.md
  _sass/base.scss
Labels: Ready, impact:submission

#525 Issue 42
  _drafts/2021-07-16-ALTF4-42.md
  assets/ALTF4/42/thumbnail.jpg
Labels: Ready, impact:submission

#511 Best of its genre - part 2
  _drafts/influence.md
Labels: Ready, impact:submission

#522 Issue 41 - Chinese Translation
  _posts/zh/2021-07-09-ALTF4-41.md
Labels: impact:translation

#526 Issue 42 - Chinese Translation
  _posts/zh/2021-07-16-ALTF4-42.md
Labels: impact:translation

#527 Issue 42 - Translation push
  _posts/fr/2021-07-16-ALTF4-42.md
Labels: impact:translation

#530 Update spidertron to minimize padding
  assets/GLOBAL/js/spidertron.js
Labels: impact:enhancement, platform:website

#531 Issue 43
  _drafts/2021-07-23-ALTF4-43.md
  assets/ALTF4/43/thumbnail.jpg
Labels: Ready, impact:submission

#519 DyWorld - History
  _drafts/dyworld-history.md
Labels: Ready, impact:submission

#533 Issue 42 - FR translation
  _posts/fr/2021-07-23-ALTF4-43.md
Labels: impact:translation

#532 Issue 43 - Chinese Translation
  _posts/zh/2021-07-23-ALTF4-43.md
Labels: impact:translation

#535 Juxtapose
  _drafts/2020-08-20-ALTF4-X.md
  _includes/juxtapose.html
  _sass/juxtapose.scss
  assets/GLOBAL/css/style.scss
Labels: impact:enhancement, platform:website

#536 Issue 44
  _drafts/2021-07-30-ALTF4-44.md
  assets/ALTF4/44/thumbnail.jpg
Labels: impact:submission

#523 Trainperspective
  _drafts/trainperspective.md
  _includes/juxtapose.html
  _includes/video.html
Labels: Ready, impact:submission

#538 Issue 44 Translations
  _posts/de/2021-07-30-ALTF4-44.md
  _posts/fr/2021-07-30-ALTF4-44.md
Labels: impact:translation

#537 Issue 44 - Chinese Translation
  _posts/zh/2021-07-30-ALTF4-44.md
Labels: impact:translation

#529 moved footer lower
  _sass/footer.scss
Labels: impact:enhancement, platform:website
