Repository AlternativeFFFF/Alt-F4, pull requests merged in 2022-04, with the labels that each got.

#618 Issue 58
  _drafts/2022-04-01-ALTF4-58.md
Labels: impact:submission

#617 Submission arpril 1st
  _drafts/submission-april-1st.md
Labels: impact:submission, New

#619 Issue58 - Translation push
  _posts/de/2022-04-01-ALTF4-58.md
  _posts/fr/2022-04-01-ALTF4-58.md
Labels: impact:translation

#621 Issue 59
  _drafts/2022-04-15-ALTF4-59.md
  assets/ALTF4/59/thumbnail.jpg
Labels: impact:submission

#620 The story of r/place
  _drafts/rplace-2022.md
Labels: impact:submission, New

#622 De fix
  _posts/de/2022-04-15-ALTF4-59.md
Labels: impact:bug, impact:translation, Editing

#625 DE fixes for ALTF4-58 and 59
  _posts/de/2022-04-01-ALTF4-58.md
  _posts/de/2022-04-15-ALTF4-59.md
Labels: impact:translation
