Repository AlternativeFFFF/Alt-F4, pull requests merged in 2022-08, with the labels that each got.

#636 Issue 63
  _drafts/2022-08-12-ALTF4.md
  assets/ALTF4/63/thumbnail.jpg
Labels: impact:submission

#614 Dana's dev blog
  _drafts/main.md
Labels: impact:submission, status:content-edit

#637 Issue63 - Translation push
  _posts/de/2022-08-12-ALTF4-63.md
  _posts/fr/2022-08-12-ALTF4-63.md
Labels: impact:translation
