Repository AlternativeFFFF/Alt-F4, pull requests merged in 2022-05, with the labels that each got.

#616 Submission burning questions
  _drafts/burning-questions.md
Labels: impact:submission, New

#630 Editor's note about drain power
  _posts/de/2022-05-06-ALTF4-60.md
  _posts/en/2022-05-06-ALTF4-60.md
  _posts/fr/2022-05-06-ALTF4-60.md
Labels: impact:translation

#631 Intro 61
  _drafts/2022-05-24-ALTF4-61.md
  assets/ALTF4/61/thumbnail.jpg
Labels: impact:submission

#628 factorio-draftsman: A Python module for creating blueprint strings
  _drafts/main.md
Labels: impact:submission, New

#632 Issue 61 - Translation push
  _posts/fr/2022-05-27-ALTF4-61.md
Labels: impact:translation
