Repository AlternativeFFFF/Alt-F4, pull requests merged in 2022-06, with the labels that each got.

#624 Fixing behaviour of 404 page
  404.html
  _posts/fr/2022-04-15-ALTF4-59.md
Labels: impact:bug, platform:website

#612 added tooltip
  _drafts/2020-08-20-ALTF4-X.md
  _includes/info.html
  _sass/tooltip.scss
  assets/GLOBAL/css/style.scss
Labels: impact:enhancement, platform:website

#629 Lawrence - Mod Comparison
  _drafts/mod-comparison.md
Labels: impact:submission, status:translation

#634 Issue 62 - Translation push
  _posts/de/2022-06-10-ALTF4-62.md
  _posts/fr/2022-06-10-ALTF4-62.md
Labels: impact:translation
